CREATE TABLE acidente_ocorrencia (
id INTEGER PRIMARY KEY,
dat_acidente date, 
hora_acidente time,
qtde_acidente INTEGER, 
id_vitima_inc INTEGER, 
nro_acidente_Km NUMERIC(10,2),
id_trecho_oco VARCHAR(100),  
id_ponto_cardeal INTEGER,
id_acidente_tip INTEGER,
qt_caminhao INTEGER,
qt_ilesos INTEGER,
qt_leve INTEGER,
qt_moderado INTEGER, 
qt_grave INTEGER,
qt_mortos INTEGER
);

CREATE TABLE Tipo_Acidente(
Id INTEGER PRIMARY KEY,
Ds_Acidente_Tipo VARCHAR(100)
);
INSERT INTO tipo_acidente VALUES(1,'tipo_de_acidente');
INSERT INTO tipo_acidente VALUES(2,'Derrapagem');
INSERT INTO tipo_acidente VALUES(3,'Abalroamento transversal');
INSERT INTO tipo_acidente VALUES(4,'Colisão traseira');
INSERT INTO tipo_acidente VALUES(5,'Abalroamento longitudinal');
INSERT INTO tipo_acidente VALUES(6,'Capotamento');
INSERT INTO tipo_acidente VALUES(7,'Colisão frontal');
INSERT INTO tipo_acidente VALUES(8,'Queda de moto');
INSERT INTO tipo_acidente VALUES(9,'Atropelamento de pedestre atravessando');
INSERT INTO tipo_acidente VALUES(10,'Atropelamento de animal');
INSERT INTO tipo_acidente VALUES(11,'Engavetamento');
INSERT INTO tipo_acidente VALUES(12,'Choque em objeto fixo');
INSERT INTO tipo_acidente VALUES(13,'Colisão Traseira');
INSERT INTO tipo_acidente VALUES(14,'Colisão com Objeto Fixo');
INSERT INTO tipo_acidente VALUES(15,'Abalr.Transversal');
INSERT INTO tipo_acidente VALUES(16,'Abalr.Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(17,'Outros tipos de acidente');
INSERT INTO tipo_acidente VALUES(18,'Tombamento');
INSERT INTO tipo_acidente VALUES(19,'Colisão Frontal');
INSERT INTO tipo_acidente VALUES(20,'Atropelamento');
INSERT INTO tipo_acidente VALUES(21,'Atropelamento de Animal');
INSERT INTO tipo_acidente VALUES(22,'Saída de Pista');
INSERT INTO tipo_acidente VALUES(23,'Abalr.Sentido Oposto');
INSERT INTO tipo_acidente VALUES(24,'Colisão Lateral');
INSERT INTO tipo_acidente VALUES(25,'Choque - Defensa, barreira ou "submarino"');
INSERT INTO tipo_acidente VALUES(26,'Queda de Bicicleta');
INSERT INTO tipo_acidente VALUES(27,'Queda de Moto');
INSERT INTO tipo_acidente VALUES(28,'Outros - Sequência');
INSERT INTO tipo_acidente VALUES(29,'Saida de Pista');
INSERT INTO tipo_acidente VALUES(30,'Colisão Transversal');
INSERT INTO tipo_acidente VALUES(31,'Atropelamento - Morador');
INSERT INTO tipo_acidente VALUES(32,'Choque - Poste');
INSERT INTO tipo_acidente VALUES(33,'Outros');
INSERT INTO tipo_acidente VALUES(34,'Choque - Arvore');
INSERT INTO tipo_acidente VALUES(35,'Choque - Outros');
INSERT INTO tipo_acidente VALUES(36,'Choque - Elemento de Drenagem');
INSERT INTO tipo_acidente VALUES(37,'Atropelamento - Ciclista');
INSERT INTO tipo_acidente VALUES(38,'Choque - Suporte de Sinalização');
INSERT INTO tipo_acidente VALUES(39,'Abalroamento Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(40,'Atropelamento - Andarilho');
INSERT INTO tipo_acidente VALUES(41,'Choque - Talude');
INSERT INTO tipo_acidente VALUES(42,'Abalroamento Sentido Oposto');
INSERT INTO tipo_acidente VALUES(43,'Atropelamento - Outros');
INSERT INTO tipo_acidente VALUES(44,'Atropelamento - Usuário');
INSERT INTO tipo_acidente VALUES(45,'Choque - Objeto sobre a pista');
INSERT INTO tipo_acidente VALUES(46,'Atropelamento - Funcionário');
INSERT INTO tipo_acidente VALUES(47,'Objeto lançado contra veículo');
INSERT INTO tipo_acidente VALUES(48,'Choque - Veiculo parado na pista');
INSERT INTO tipo_acidente VALUES(49,'Choque - Veiculo parado no acostamento');
INSERT INTO tipo_acidente VALUES(50,'Atropelamento - Sem Informação');
INSERT INTO tipo_acidente VALUES(51,'Atropelamento - Ambulante');
INSERT INTO tipo_acidente VALUES(52,'');
INSERT INTO tipo_acidente VALUES(53,'Acidentes de outra natureza');
INSERT INTO tipo_acidente VALUES(54,'Colisão com veículos (traseira)');
INSERT INTO tipo_acidente VALUES(55,'Colisão lateral no mesmo sentido');
INSERT INTO tipo_acidente VALUES(56,'Colisão c/ obstáculos');
INSERT INTO tipo_acidente VALUES(57,'Saídas de pista');
INSERT INTO tipo_acidente VALUES(58,'Colisão lateral no sentido contrário');
INSERT INTO tipo_acidente VALUES(59,'Colisão com veículos (frontal)');
INSERT INTO tipo_acidente VALUES(60,'Atropelamento de pedestre');
INSERT INTO tipo_acidente VALUES(61,'Atropelamento de animais');
INSERT INTO tipo_acidente VALUES(62,'Colisão Lateral Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(63,'Atropelamento - Animal');
INSERT INTO tipo_acidente VALUES(64,'Atropelamento - Pedestre');
INSERT INTO tipo_acidente VALUES(65,'Acidente - Outra Natureza');
INSERT INTO tipo_acidente VALUES(66,'Abalroamento - Sentido Oposto');
INSERT INTO tipo_acidente VALUES(67,'Colisão Lateral Sentido Oposto');
INSERT INTO tipo_acidente VALUES(68,'Abalroamento - Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(69,'Atropelamento - Pedestre Usuário');
INSERT INTO tipo_acidente VALUES(70,'Atropelamento - PedestreFuncionário');
INSERT INTO tipo_acidente VALUES(71,'Atropelamento - Pedestre Andarilho');
INSERT INTO tipo_acidente VALUES(72,'Derramamento de Carga');
INSERT INTO tipo_acidente VALUES(73,'Norte');
INSERT INTO tipo_acidente VALUES(74,'Sul');
INSERT INTO tipo_acidente VALUES(75,'Choque');
INSERT INTO tipo_acidente VALUES(76,'Saída de pista');
INSERT INTO tipo_acidente VALUES(77,'Colisão transversal');
INSERT INTO tipo_acidente VALUES(78,'Colisão lateral em sentido contrário');
INSERT INTO tipo_acidente VALUES(79,'Atropelamento de ciclista');
INSERT INTO tipo_acidente VALUES(80,'Choque - Cancela de Pedagio');
INSERT INTO tipo_acidente VALUES(81,'Choque - Objeto não identificado');
INSERT INTO tipo_acidente VALUES(82,'Soterramento');
INSERT INTO tipo_acidente VALUES(83,'Incêndio');
INSERT INTO tipo_acidente VALUES(84,'Submersão');
INSERT INTO tipo_acidente VALUES(85,'Explosão');
INSERT INTO tipo_acidente VALUES(86,'Transposição de Pista');
INSERT INTO tipo_acidente VALUES(87,'Queda');
INSERT INTO tipo_acidente VALUES(88,'Não Def');
INSERT INTO tipo_acidente VALUES(89,'Não Def.');
INSERT INTO tipo_acidente VALUES(90,'Travessia Canteiro Central');
INSERT INTO tipo_acidente VALUES(91,'Problema Mecanico / Eletrico');
INSERT INTO tipo_acidente VALUES(92,'Choque - Defensa, barreira ou  submarino');
INSERT INTO tipo_acidente VALUES(93,'Choque Contra Objeto Fixo');
INSERT INTO tipo_acidente VALUES(94,'Atropelamento de Pedestre');
INSERT INTO tipo_acidente VALUES(95,'Sequência');
INSERT INTO tipo_acidente VALUES(96,'Carreta deu L');
INSERT INTO tipo_acidente VALUES(97,'Queda de Ciclista');
INSERT INTO tipo_acidente VALUES(98,'Outros - seguências');
INSERT INTO tipo_acidente VALUES(99,'Outros - sequências');
INSERT INTO tipo_acidente VALUES(100,'Choque - Poste/');
INSERT INTO tipo_acidente VALUES(101,'Choque- Placa/Suporte Sinalização');
INSERT INTO tipo_acidente VALUES(102,'Choque- Poste/Equipamento');
INSERT INTO tipo_acidente VALUES(103,'Choque - Barreira');
INSERT INTO tipo_acidente VALUES(104,'Choque - Defensa');
INSERT INTO tipo_acidente VALUES(105,'Atropelamento - Morador/Trabalhador');
INSERT INTO tipo_acidente VALUES(106,'Queda em Ribanceira');
INSERT INTO tipo_acidente VALUES(107,'Choque - Submarino');
INSERT INTO tipo_acidente VALUES(108,'Queda de Ponte/Viaduto');
INSERT INTO tipo_acidente VALUES(109,'Choque - Cabine de Pedágio');
INSERT INTO tipo_acidente VALUES(110,'Atropelamento - Esportista/Romeiro');
INSERT INTO tipo_acidente VALUES(111,'Queda de bicicleta');
INSERT INTO tipo_acidente VALUES(112,'Choque - Objeto Fixo');
INSERT INTO tipo_acidente VALUES(113,'Choque em objeto na pista');
INSERT INTO tipo_acidente VALUES(114,'choque - Objeto Fixo');
INSERT INTO tipo_acidente VALUES(115,'Colisão veiculo parado acostamento');
INSERT INTO tipo_acidente VALUES(116,'Choque com objeto na pista');
INSERT INTO tipo_acidente VALUES(117,'Abalroamento - Longitudinal');
INSERT INTO tipo_acidente VALUES(118,'Abalroamento - Transversal');
INSERT INTO tipo_acidente VALUES(119,'Queda de Carga');
INSERT INTO tipo_acidente VALUES(120,'Atropelamento - Pedestre atravessando');
INSERT INTO tipo_acidente VALUES(121,'Choque-outros');
INSERT INTO tipo_acidente VALUES(122,'Atropel. de pedestre atravessando');
INSERT INTO tipo_acidente VALUES(123,'Atropel. de pedestre caminhando');
INSERT INTO tipo_acidente VALUES(124,'Choque em defensa');
INSERT INTO tipo_acidente VALUES(125,'Queda de carga');
INSERT INTO tipo_acidente VALUES(126,'Choque em barreira New Jersey');
INSERT INTO tipo_acidente VALUES(127,'Choque em veículo parado na pista');
INSERT INTO tipo_acidente VALUES(128,'derrapagem');
INSERT INTO tipo_acidente VALUES(129,'Atropelamento em abrigo de ônibus');
INSERT INTO tipo_acidente VALUES(130,'choque em objeto fixo');
INSERT INTO tipo_acidente VALUES(131,'Abalroamento Longitudinal');
INSERT INTO tipo_acidente VALUES(132,'colisão Frontal');
INSERT INTO tipo_acidente VALUES(133,'Choque em Objeto Fixo');
INSERT INTO tipo_acidente VALUES(134,'colisão frontal');
INSERT INTO tipo_acidente VALUES(135,'Choque em Objeto fixo');
INSERT INTO tipo_acidente VALUES(136,'Imprudência');
INSERT INTO tipo_acidente VALUES(137,'colisão traseira');
INSERT INTO tipo_acidente VALUES(138,'capotamento');
INSERT INTO tipo_acidente VALUES(139,'Abalroamento Transversal');
INSERT INTO tipo_acidente VALUES(140,'Atropelamento - Pessoa');
INSERT INTO tipo_acidente VALUES(141,'Atropelamento de Cachorro');
INSERT INTO tipo_acidente VALUES(142,'Queda de vegetação c/ veículo');
INSERT INTO tipo_acidente VALUES(143,'Atropelamento - Cachorro');
INSERT INTO tipo_acidente VALUES(144,'Colisão');
INSERT INTO tipo_acidente VALUES(145,'Atropelamento Animal');
INSERT INTO tipo_acidente VALUES(146,'Queda de ciclista');
INSERT INTO tipo_acidente VALUES(147,'Choque com Objeto Fixo');
INSERT INTO tipo_acidente VALUES(148,'Veículo em Chamas');
INSERT INTO tipo_acidente VALUES(149,'Choque com Veículo Estacionado');
INSERT INTO tipo_acidente VALUES(150,'Atropelamento de Equino');
INSERT INTO tipo_acidente VALUES(151,'Atropelamento e Fuga');
INSERT INTO tipo_acidente VALUES(152,'Atropelamento de Bovino');
INSERT INTO tipo_acidente VALUES(153,'Danos Eventuais');
INSERT INTO tipo_acidente VALUES(154,'Colisão com ciclista');
INSERT INTO tipo_acidente VALUES(155,'Atropelamento - Bovino');
INSERT INTO tipo_acidente VALUES(156,'Atropelamento - Equino');
INSERT INTO tipo_acidente VALUES(157,'Atropelamento - Bubalino');
INSERT INTO tipo_acidente VALUES(158,'Choque na cancela');
INSERT INTO tipo_acidente VALUES(159,'Desatrelamento');
INSERT INTO tipo_acidente VALUES(160,'Choque - Barranco');
INSERT INTO tipo_acidente VALUES(161,'Choque - Defensa, barreira ou meio fio');
INSERT INTO tipo_acidente VALUES(162,'Choque - Obstáculo Fixo');
INSERT INTO tipo_acidente VALUES(163,'Choque - Sinalização');
INSERT INTO tipo_acidente VALUES(164,'Choque - New jersey');
INSERT INTO tipo_acidente VALUES(165,'Choque - Meio fio');
INSERT INTO tipo_acidente VALUES(166,'Choque - Defensa metálica');
INSERT INTO tipo_acidente VALUES(167,'Queda de barreira, ribanceira, ponte ou viaduto');
INSERT INTO tipo_acidente VALUES(168,'Choque na praça ? submarino');
INSERT INTO tipo_acidente VALUES(169,'Queda de veículo em ribanceira, ponte ou viaduto');
INSERT INTO tipo_acidente VALUES(170,'Choque - Talude ou Barranco');
INSERT INTO tipo_acidente VALUES(171,'Queda de Carro');
INSERT INTO tipo_acidente VALUES(172,'Colisão - Traseira');
INSERT INTO tipo_acidente VALUES(173,'Choque com objeto sobre a pista');
INSERT INTO tipo_acidente VALUES(174,'Colisão - Lateral');
INSERT INTO tipo_acidente VALUES(175,'Choque Defensa');
INSERT INTO tipo_acidente VALUES(176,'Choque Praça - Cabine');
INSERT INTO tipo_acidente VALUES(177,'Colisão - Transversal');
INSERT INTO tipo_acidente VALUES(178,'Colisão - Frontal');
INSERT INTO tipo_acidente VALUES(179,'Choque com veículo na faixa de');
INSERT INTO tipo_acidente VALUES(180,'Choque Barreira');
INSERT INTO tipo_acidente VALUES(181,'Choque - Meio Fio');
INSERT INTO tipo_acidente VALUES(182,'Choque com objeto sobre a pist');
INSERT INTO tipo_acidente VALUES(183,'Choque - Pilar');
INSERT INTO tipo_acidente VALUES(184,'Choque - Canaleta');
INSERT INTO tipo_acidente VALUES(185,'Choque Praça');
INSERT INTO tipo_acidente VALUES(186,'Choque Talude');
INSERT INTO tipo_acidente VALUES(187,'Choque veículo parado na pista');
INSERT INTO tipo_acidente VALUES(188,'Atropelamento Ciclista');
INSERT INTO tipo_acidente VALUES(189,'Queda de Ponte / Viaduto');
INSERT INTO tipo_acidente VALUES(190,'Choque - Veículo parado na pista');
INSERT INTO tipo_acidente VALUES(191,'Abalr. Transversal');
INSERT INTO tipo_acidente VALUES(192,'Abalr. Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(193,'Abalr. Sentido Oposto');
INSERT INTO tipo_acidente VALUES(194,'Colisão com Veículo Estac.');
INSERT INTO tipo_acidente VALUES(195,'Atropelamento sem morte');
INSERT INTO tipo_acidente VALUES(196,'Outros(especificar)');
INSERT INTO tipo_acidente VALUES(197,'Atropelamento com morte');
INSERT INTO tipo_acidente VALUES(198,'Colisão com objeto Fixo');
INSERT INTO tipo_acidente VALUES(199,'Outros Tipos de Acidente');
INSERT INTO tipo_acidente VALUES(200,'Colisão com Objeto fixo');
INSERT INTO tipo_acidente VALUES(201,'Abal. Sentido Oposto');
INSERT INTO tipo_acidente VALUES(202,'Colisão com objeto fixo');
INSERT INTO tipo_acidente VALUES(203,'Abalroamento no Mesmo Sentido');
INSERT INTO tipo_acidente VALUES(204,'Abalr. Sentido Oposto.');
INSERT INTO tipo_acidente VALUES(205,'Outros Tipos');
INSERT INTO tipo_acidente VALUES(206,'Saída de  Pista');
INSERT INTO tipo_acidente VALUES(207,'Abalroamento transversal.');
INSERT INTO tipo_acidente VALUES(208,'Outros Tipos de acidente');
INSERT INTO tipo_acidente VALUES(209,'Abalrroamento Transversal.');
INSERT INTO tipo_acidente VALUES(210,'Colisão objeto fixo');
INSERT INTO tipo_acidente VALUES(211,'Saida de pista');
INSERT INTO tipo_acidente VALUES(212,'Abalr.mesmo sentido');
INSERT INTO tipo_acidente VALUES(213,'Abalroamento mesmo sentido');
INSERT INTO tipo_acidente VALUES(214,'Abalroamento em Sent.Oposto');
INSERT INTO tipo_acidente VALUES(215,'Abalroamento no mesmo Sentido');
INSERT INTO tipo_acidente VALUES(216,'Abalroamento sentido Oposto');
INSERT INTO tipo_acidente VALUES(217,'Abalroamento em sentido oposto');
INSERT INTO tipo_acidente VALUES(218,'Abalroamento no mesmo sentido');
INSERT INTO tipo_acidente VALUES(219,'Abalroamanento Traversasl');
INSERT INTO tipo_acidente VALUES(220,'Abalroamento  no mesmo sentido');
INSERT INTO tipo_acidente VALUES(221,'Colisão com veículo estacionado');
INSERT INTO tipo_acidente VALUES(222,'atropelamento');
INSERT INTO tipo_acidente VALUES(223,'Abalroamento Trarnversal');
INSERT INTO tipo_acidente VALUES(224,'Outros tipos de Acidente');
INSERT INTO tipo_acidente VALUES(225,'abalr.mesmo Sentido');
INSERT INTO tipo_acidente VALUES(226,'Abalroamento em mesmo sentido');
INSERT INTO tipo_acidente VALUES(227,'Abalromanemto mesmo sentido');
INSERT INTO tipo_acidente VALUES(228,'Abalroamente Transversal');
INSERT INTO tipo_acidente VALUES(229,'Abalr.Sent.Oposto');
INSERT INTO tipo_acidente VALUES(230,'Abalr.em mesmo sentido');
INSERT INTO tipo_acidente VALUES(231,'Abalr.Mesmo sentido');
INSERT INTO tipo_acidente VALUES(232,'Ablr.Sentido Oposto');
INSERT INTO tipo_acidente VALUES(233,'Colisão Ojeto Fixo');
INSERT INTO tipo_acidente VALUES(234,'Abal.mesmo sentido');
INSERT INTO tipo_acidente VALUES(235,'Abalr. Mesmo sentido');
INSERT INTO tipo_acidente VALUES(236,'Colisão Objeto Fixo');
INSERT INTO tipo_acidente VALUES(237,'Abal.mesmo.sentido');
INSERT INTO tipo_acidente VALUES(238,'Abal.sentido. Oposto');
INSERT INTO tipo_acidente VALUES(239,'Abal.Transversal');
INSERT INTO tipo_acidente VALUES(240,'Abal.sent.oposto');
INSERT INTO tipo_acidente VALUES(241,'Abalr.sentido oposto');
INSERT INTO tipo_acidente VALUES(242,'Abalr. Sentido oposto');
INSERT INTO tipo_acidente VALUES(243,'abalr. Transversal');
INSERT INTO tipo_acidente VALUES(244,'Tombamento de moto');
INSERT INTO tipo_acidente VALUES(245,'Colisão Traseira - veículos');
INSERT INTO tipo_acidente VALUES(246,'Colisão com Obstáculos');
INSERT INTO tipo_acidente VALUES(247,'Colisão Lateral - sentido contrário');
INSERT INTO tipo_acidente VALUES(248,'Colisão Lateral - mesmo sentido');
INSERT INTO tipo_acidente VALUES(249,'Colisão Frontal - veículos');
INSERT INTO tipo_acidente VALUES(250,'Tombamento de Moto');
INSERT INTO tipo_acidente VALUES(251,'Atropelamento de pedestre caminhando');
INSERT INTO tipo_acidente VALUES(252,'Queda de ribanceira');
INSERT INTO tipo_acidente VALUES(253,'Choque em Barreira New Jersey');
INSERT INTO tipo_acidente VALUES(254,'Choque em Defensa');
INSERT INTO tipo_acidente VALUES(255,'Atropelamento de Pedestre Atravessando');
INSERT INTO tipo_acidente VALUES(256,'Atropelamento de Pedestre Caminhando');
INSERT INTO tipo_acidente VALUES(257,'Queda de ponte/viaduto');
INSERT INTO tipo_acidente VALUES(258,'Atropelamento - Pedestre caminhando');
INSERT INTO tipo_acidente VALUES(259,'Choque contra Objeto Fixo');
INSERT INTO tipo_acidente VALUES(260,'Atropelamento  de Pedestre');
INSERT INTO tipo_acidente VALUES(261,'Atropelamento de Ciclista');
INSERT INTO tipo_acidente VALUES(262,'Choque na Praça - Cabine');
INSERT INTO tipo_acidente VALUES(263,'Choque contra objeto na faixa de rolamento');
INSERT INTO tipo_acidente VALUES(264,'Choque na Praça - Submarino');
INSERT INTO tipo_acidente VALUES(265,'INCIDENTE - Choque na Praça - Cancela');
INSERT INTO tipo_acidente VALUES(266,'Queda de carga sobre a pista');
INSERT INTO tipo_acidente VALUES(267,'Incidente');
INSERT INTO tipo_acidente VALUES(268,'Colisão na Praça - Cancela');
INSERT INTO tipo_acidente VALUES(269,'INCIDENTE - Colisão na Praça - Cancela');
INSERT INTO tipo_acidente VALUES(270,'Colisão na Praça - Submarino');
INSERT INTO tipo_acidente VALUES(271,'Choque contra veículo no acostamento');
INSERT INTO tipo_acidente VALUES(272,'Não Localizado / Evadiu-se');
INSERT INTO tipo_acidente VALUES(273,'Choque com objeto fixo');
INSERT INTO tipo_acidente VALUES(274,'Atropelamento - Abrigo de ônibus');
INSERT INTO tipo_acidente VALUES(275,'Colisão lateral');
INSERT INTO tipo_acidente VALUES(276,'Choque c/ Objeto Fixo');
INSERT INTO tipo_acidente VALUES(277,'Queda Veículo');
INSERT INTO tipo_acidente VALUES(278,'Queda de Ribanceira');
INSERT INTO tipo_acidente VALUES(279,'Choque / defensa, barreira ou "submarino"');
INSERT INTO tipo_acidente VALUES(280,'Choque / árvore');
INSERT INTO tipo_acidente VALUES(281,'Atropelamento de Andarilho');
INSERT INTO tipo_acidente VALUES(282,'Choque com objeto');
INSERT INTO tipo_acidente VALUES(283,'Queda de Viaduto');
INSERT INTO tipo_acidente VALUES(284,'Choque / objeto não identificado');
INSERT INTO tipo_acidente VALUES(285,'Choque c/ Veículo Parado');
INSERT INTO tipo_acidente VALUES(286,'Colisão com veículo da concessionária');
INSERT INTO tipo_acidente VALUES(287,'Choque com veículo da concessionária estacionado');
INSERT INTO tipo_acidente VALUES(288,'Choque com veículo na faixa de rolamento');
INSERT INTO tipo_acidente VALUES(289,'Atropelamento - Morador/Trabalhador/Estudante');
INSERT INTO tipo_acidente VALUES(290,'Choque Praça - Submarino');
INSERT INTO tipo_acidente VALUES(291,'Atropelamento - Suicida');
INSERT INTO tipo_acidente VALUES(292,'Choque - Caixa de Captação/Fibra');
INSERT INTO tipo_acidente VALUES(293,'Choque com veículo no acostamento');
INSERT INTO tipo_acidente VALUES(294,'Atropelamento - Esportista');
INSERT INTO tipo_acidente VALUES(295,'Teste Wanderson');
INSERT INTO tipo_acidente VALUES(296,'Choque - Painel Propaganda');

CREATE TABLE Ponto_Cardeal(
Id integer,
Ds_ponto_cardeal varchar(100)
);
INSERT INTO Ponto_Cardeal values (1,'Sul');
INSERT INTO Ponto_Cardeal values (2,'Norte');
INSERT INTO Ponto_Cardeal values (3,'Leste');
INSERT INTO Ponto_Cardeal values (4,'Oeste');

CREATE TABLE Trecho(
Id INTEGER PRIMARY KEY,
Ds_trecho varchar(200)
)
INSERT INTO trecho VALUES(1,'BR-393/RJ');
INSERT INTO trecho VALUES(2,'Alça Sul');
INSERT INTO trecho VALUES(3,'Alça Sul (Estrada União Indústria)/RJ');
INSERT INTO trecho VALUES(4,'BR-381/SP');
INSERT INTO trecho VALUES(5,'BR-381/MG');
INSERT INTO trecho VALUES(6,'BR-381/MG-CONT');
INSERT INTO trecho VALUES(7,'Contorno/MG');
INSERT INTO trecho VALUES(8,'BR-101/RJ');
INSERT INTO trecho VALUES(9,'BR-101/SC');
INSERT INTO trecho VALUES(10,'BR-116/PR');
INSERT INTO trecho VALUES(11,'BR-376/PR');
INSERT INTO trecho VALUES(12,'BR-116/SC');
INSERT INTO trecho VALUES(13,'BR-376/SC');
INSERT INTO trecho VALUES(14,'BR-116/CW');
INSERT INTO trecho VALUES(15,'BR-116/SP');
INSERT INTO trecho VALUES(16,'CW-116/SP');
INSERT INTO trecho VALUES(17,'BR-324/BA');
INSERT INTO trecho VALUES(18,'BR-116/BA - ContSuFS');
INSERT INTO trecho VALUES(19,'BR-116/BA');
INSERT INTO trecho VALUES(20,'BR-116/BA - Cont VC');
INSERT INTO trecho VALUES(21,'BA-528');
INSERT INTO trecho VALUES(22,'BA-526');
INSERT INTO trecho VALUES(23,'CONTORNO - VC/BA');
INSERT INTO trecho VALUES(24,'526/BA');
INSERT INTO trecho VALUES(25,'CONTORNO SUL  - FS/BA');
INSERT INTO trecho VALUES(26,'CONTORNO NORTE - FS - 116/BA');
INSERT INTO trecho VALUES(27,'528/BA');
INSERT INTO trecho VALUES(28,'BR-060/DF');
INSERT INTO trecho VALUES(29,'BR-153/GO');
INSERT INTO trecho VALUES(30,'BR-153/MG');
INSERT INTO trecho VALUES(31,'BR-060/GO');
INSERT INTO trecho VALUES(32,'BR-262/MG');
INSERT INTO trecho VALUES(33,'BR-262/GO');
INSERT INTO trecho VALUES(34,'BR-60/GO');
INSERT INTO trecho VALUES(35,'BR-040/RJ');
INSERT INTO trecho VALUES(36,'BR-040/MG');
INSERT INTO trecho VALUES(37,'BR-163/MT');
INSERT INTO trecho VALUES(38,'BR-364/MT');
INSERT INTO trecho VALUES(39,'BR-070/MT');
INSERT INTO trecho VALUES(40,'BR-70/MT');
INSERT INTO trecho VALUES(41,'BR-116/RJ');
INSERT INTO trecho VALUES(42,'BR-101/ES');
INSERT INTO trecho VALUES(43,'BR-101/BA');
INSERT INTO trecho VALUES(44,'BR-101/ES (Contorno de Vitória)');
INSERT INTO trecho VALUES(45,'BR-101/ES (Contorno de Iconha)');
INSERT INTO trecho VALUES(46,'BR-101/ES (Contorno Iconha)');
INSERT INTO trecho VALUES(47,'Contorno de Iconha/ES');
INSERT INTO trecho VALUES(48,'BR-050/MG');
INSERT INTO trecho VALUES(49,'BR-050/GO');
INSERT INTO trecho VALUES(50,'Contorno');
INSERT INTO trecho VALUES(51,'CONTORNO');
INSERT INTO trecho VALUES(52,'BR-50/MG');
INSERT INTO trecho VALUES(53,'Contorno de Uberlândia/MG');
INSERT INTO trecho VALUES(54,'Acessos Niterói');
INSERT INTO trecho VALUES(55,'Subida do Vão Central');
INSERT INTO trecho VALUES(56,'Mocangue');
INSERT INTO trecho VALUES(57,'Cajú');
INSERT INTO trecho VALUES(58,'Descida do Vão Central');
INSERT INTO trecho VALUES(59,'Emergência I');
INSERT INTO trecho VALUES(60,'Curvão');
INSERT INTO trecho VALUES(61,'Retão');
INSERT INTO trecho VALUES(62,'Vão Central');
INSERT INTO trecho VALUES(63,'Praça de Pedágio');
INSERT INTO trecho VALUES(64,'Emergência II');
INSERT INTO trecho VALUES(65,'PT');
INSERT INTO trecho VALUES(66,'N03');
INSERT INTO trecho VALUES(67,'N10');
INSERT INTO trecho VALUES(68,'R1');
INSERT INTO trecho VALUES(69,'N01');
INSERT INTO trecho VALUES(70,'R2A');
INSERT INTO trecho VALUES(71,'R3');
INSERT INTO trecho VALUES(72,'N11');
INSERT INTO trecho VALUES(73,'N09');
INSERT INTO trecho VALUES(74,'N12');
INSERT INTO trecho VALUES(75,'N08');
INSERT INTO trecho VALUES(76,'N13');
INSERT INTO trecho VALUES(77,'N14');
INSERT INTO trecho VALUES(78,'MERGULHÃO');
INSERT INTO trecho VALUES(79,'R4');
INSERT INTO trecho VALUES(80,'Acesso N 08/RJ');
INSERT INTO trecho VALUES(81,'Acesso R 2/RJ');
INSERT INTO trecho VALUES(82,'Acesso N 13/RJ');
INSERT INTO trecho VALUES(83,'Acesso R 1/RJ');
INSERT INTO trecho VALUES(84,'Acesso N 09/RJ');
INSERT INTO trecho VALUES(85,'Acesso N 07/RJ');
INSERT INTO trecho VALUES(86,'Acesso N 12/RJ');
INSERT INTO trecho VALUES(87,'Acesso N 02/RJ');
INSERT INTO trecho VALUES(88,'Acesso R 2 A/RJ');
INSERT INTO trecho VALUES(89,'Acesso N 06/RJ');
INSERT INTO trecho VALUES(90,'Acesso N 03/RJ');
INSERT INTO trecho VALUES(91,'Acesso N 19/RJ');
INSERT INTO trecho VALUES(92,'Acesso N 05/RJ');
INSERT INTO trecho VALUES(93,'Acesso N 10/RJ');
INSERT INTO trecho VALUES(94,'Acesso N 04/RJ');
INSERT INTO trecho VALUES(95,'Acesso N 17/RJ');
INSERT INTO trecho VALUES(96,'Acesso N 11/RJ');
INSERT INTO trecho VALUES(97,'Acesso N 14/RJ');
INSERT INTO trecho VALUES(98,'Acesso N 18/RJ');
INSERT INTO trecho VALUES(99,'Acesso N 01/RJ');
INSERT INTO trecho VALUES(100,'Acesso R 4/RJ');
INSERT INTO trecho VALUES(101,'Acesso N 11 A/RJ');
INSERT INTO trecho VALUES(102,'BR-116/RS');
INSERT INTO trecho VALUES(103,'BR-392/RS');
INSERT INTO trecho VALUES(104,'BR-604/RS');
INSERT INTO trecho VALUES(105,'BR-293/RS');
INSERT INTO trecho VALUES(106,'BR-364/GO');
INSERT INTO trecho VALUES(107,'BR-365/MG');
INSERT INTO trecho VALUES(108,'BR-364/MG');
INSERT INTO trecho VALUES(109,'BR-101/SP');
INSERT INTO trecho VALUES(110,'BR-163/MS');
INSERT INTO trecho VALUES(111,'BR-153/SP');
INSERT INTO trecho VALUES(112,'BR-040/GO');
INSERT INTO trecho VALUES(113,'BR-040/DF');
INSERT INTO trecho VALUES(114,'Fora_Rota');
INSERT INTO trecho VALUES(115,'BR-40/MG');
INSERT INTO trecho VALUES(116,'BR-101/RS');
INSERT INTO trecho VALUES(117,'BR-386/RS');
INSERT INTO trecho VALUES(118,'BR-290/RS');
INSERT INTO trecho VALUES(119,'BR-448/RS');

