INSERT INTO concessionaria values(1,'RODOVIA DO AÇO');
INSERT INTO concessionaria values(2,'AUTOPISTA FERNÃO DIAS');
INSERT INTO concessionaria values(3,'AUTOPISTA FLUMINENSE');
INSERT INTO concessionaria values(4,'AUTOPISTA LITORAL SUL');
INSERT INTO concessionaria values(5,'AUTOPISTA PLANALTO SUL');
INSERT INTO concessionaria values(6,'AUTOPISTA REGIS');
INSERT INTO concessionaria values(7,'VIA BAHIA');
INSERT INTO concessionaria values(8,'CONCEBRA');
INSERT INTO concessionaria values(9,'CONCER');
INSERT INTO concessionaria values(10,'CRO');
INSERT INTO concessionaria values(11,'CRT');
INSERT INTO concessionaria values(12,'ECO101');
INSERT INTO concessionaria values(13,'ECO050');
INSERT INTO concessionaria values(14,'ECOPONTE');
INSERT INTO concessionaria values(15,'ECOSUL');
INSERT INTO concessionaria values(16,'ECOVIAS DO CERRADO');
INSERT INTO concessionaria values(17,'MSVIA');
INSERT INTO concessionaria values(18,'NOVA DUTRA');
INSERT INTO concessionaria values(19,'TRANSBRASILIANA');
INSERT INTO concessionaria values(20,'VIA040');
INSERT INTO concessionaria values(21,'VIA COSTEIRA');
INSERT INTO concessionaria values(22,'VIA SUL');